FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

WORKDIR /app

RUN ls

RUN pip install poetry

COPY poetry.lock pyproject.toml ./

# disable virtualenv for poetry
RUN poetry config virtualenvs.create false

RUN poetry install --no-root --no-dev

COPY . ./

ENV MAX_WORKERS=1

WORKDIR url_shortener/backend