version: "3"

services:
  backend:
    image: url_shortener:backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: url-shortener-backend
    ports:
      - "8000:80"
    entrypoint:
      - /start-reload.sh
    volumes:
      - ./url_shortener/backend:/app/url_shortener/backend
    depends_on:
      - database

  frontend:
    image: url_shortener:frontend
    build:
      context: url_shortener/frontend/url_shortener/
      dockerfile: Dockerfile.frontend
    container_name: url-shortener-frontend
    ports:
      - "8080:8080"
    volumes:
      - ./url_shortener/frontend/url_shortener:/app
    depends_on:
      - backend

  database:
    image: 'mongo'
    container_name: url-shortener-database
    ports:
      - '27017:27017'
    environment:
      - USER_ID=1001
      - GROUP_ID=1001
    volumes:
      - ./data/db:/data/db