FROM tiangolo/uvicorn-gunicorn-fastapi:python3.7

WORKDIR /app

RUN pip install poetry

COPY poetry.lock pyproject.toml ./

RUN poetry install --no-root --no-dev

# disable virtualenv for peotry
RUN poetry config virtualenvs.create false

COPY . ./

ENV MAX_WORKERS=1

WORKDIR url_shortener/backend